### ISSUE TITLE
No reponse from the app

### ISSUE THREAD

**Issue by dcruveiller** [hvfrancesco/SLE4442-card-manager#1]
Hi
when i click connetti there is no response from the app. my SLE4442 card is connected via my smartcard reader on USB.
the log from the app says : `Exception: Failed to establish context : Service not available.`
So if you have an idea please tell me.
Thanks

**Comment by dcruveiller** [comment]
i just make the app response juste need to install pcscd and the app works ow i get Exception: Unable to connect: Card is unpowered with my SLE4442 but how to power ?

**Comment by dcruveiller** [comment]
And just for making the app response i installed pcscd and the app works

**Comment by KA7640** [comment]
Its because you have a reader that can not create a synchronous connection with the card (which an SLE4442/FM4442 needs). I am using an HID OMNIKEY 3121 and it is working perfectly.
